---
- name: Create a test directory on Debian
  hosts: all
  become: yes
  tasks:
    - name: Ensure the /test directory exists
      file:
        path: /test
        state: directory
        mode: '0755'
    - name: Remove "foo" package
      ansible.builtin.apt:
        name: nano
        state: absent
